# Generated by Django 4.1 on 2022-10-12 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True, validators=[django.core.validators.MaxLengthValidator(4096)]),
        ),
    ]
