# Generated by Django 4.1 on 2022-10-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='last_modified',
            new_name='bid_place_date',
        ),
    ]
